### ISSUE TITLE
S2LPLibrary_Examples

### ISSUE THREAD

**Issue by tobbad** [benwaffle/S2LP#1]
Hello
In your github s2lp I can not find the S2LPLibrary_Examples in your page:
https://benwaffle.github.io/S2LP/files.html
Could you publish please as well this libraray?

Regards
Tobias
![grafik](https://github.com/benwaffle/S2LP/assets/6281553/b1574c2d-ace2-496d-9edf-82a6dfc297cf)

**Comment by benwaffle** [comment]
Sorry, this repo is not maintained
